version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kamil
      MYSQL_DATABASE: taskmanager  # To opcjonalne, możesz ustawić domyślną bazę danych


    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: